spring:
    datasource:
        continue-on-error: false
        driver-class-name: org.mariadb.jdbc.Driver
        initialization-mode: always
        url: jdbc:mariadb://localhost:3306/xTASKS?createDatabaseIfNotExist=true
        username: username
        password: password
    jackson:
        serialization:
            fail-on-empty-beans: false
    jpa:
        hibernate:
            ddl-auto: update